### ISSUE TITLE
Unintentional Bolding 

### ISSUE THREAD

**Issue by amilajack** [codrops/CreativeLinkEffects#4]
https://drive.google.com/folderview?id=0B62q4hLyBtKbTUoxM0FrWFJldjQ&usp=drive_web

The google drive directory above contains the CSS and HTML file I am working. (the files are in the CSS folder). Whenever I rollover the links (home, sell, buy, etc) in chrome, the text from a bottom div starts to bold. What is causing the problem and how can I prevent this?

**Comment by crnacura** [comment]
Please provide a live version of your markup and styles (JSFiddle, Codepen, etc.).

**Comment by amilajack** [comment]
http://jsfiddle.net/fNL7V/
